server:
  #应用端口
  port: 9010
  
eureka:
  instance:
     #客户端在注册时使用自己的IP而不是主机名，默认为false
    prefer-ip-address: true
    #应用实例IP
    ip-address: 127.0.0.1     
    #eureka服务器在接受到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认90秒
    lease-expiration-duration-in-seconds: 90
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然活着，默认30秒
    lease-renewal-interval-in-seconds: 30
  client:
    service-url: # EurekaServer的地址，集群时多个注册中心地址以逗号分隔。
      defaultZone: http://p1:9000/eureka

spring:
  datasource: #mysql的配置
    url: jdbc:mysql://1.116.226.147:3306/member?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql@958958
    schema:
    - classpath:member.sql
    data:
    # - classpath:member-online-user-data.sql # 仅在第一次数据初始化时使用
     - classpath:member-view.sql
    initialization-mode: always
  #reids   
  redis:
    host: 1.116.226.147
    port: 6379
    password: redis@958958

mybatis-plus:
  #mapper配置文件
  mapper-locations:
  - classpath*:mapping/*.xml
  #指定entity扫描包类让mybatis自定扫描到自定义的entity
  type-aliases-package: com.explore.model.member
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
  