server:
  #应用端口
  port: 9001

eureka:
  instance:
    #应用实例主机名
    hostname: p1
    #eureka服务器在接受到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认90秒
    lease-expiration-duration-in-seconds: 90
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然活着，默认30秒
    lease-renewal-interval-in-seconds: 30
    #客户端在注册时使用自己的IP而不是主机名，默认为false
    prefer-ip-address: false
    #应用实例IP
    ip-address: 127.0.0.1
  client:
    service-url: # EurekaServer的地址，集群时多个注册中心地址以逗号分隔。
      defaultZone:  http://p1:9001/eureka,http://p2:9002/eureka,http://p3:9003/eureka
    #是否注册自己的信息到EurekaServer，默认是true
    register-with-eureka: true
    #是否拉取其它服务的信息，默认是true
    fetch-registry: true
    #eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds: 30
  server:
    #开启自我保护模式（开启状态下服务停掉eureka不会立即清除掉宕掉的服务），默认是true
    enable-self-preservation: false
    #eureka服务器清理无效节点,默认60*1000毫秒,即60秒
    eviction-interval-timer-in-ms: 60000
  